name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v3
    - id: build-vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'Phundrak'
        reponame: 'visu-donnees-massives'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
